import type { ProcessDefinition } from './gateway-processes';

/**
 * Catalogo dei process del gateway FD_DataServiceGatewayCrypt.php usati dal frontend.
 *
 * Gli id sono token opachi cifrati che il PHP risolve nella stored procedure da chiamare.
 * `kind` distingue letture e scritture (usato dalla modalità sola lettura); `params` e
 * `returns` documentano il contratto e sono la base per la futura API NestJS
 * (vedi docs/gateway-processes.md, generato da scripts/gateway-processes-doc.ts).
 */
export const PROCESS_DEFINITIONS = {
  // Home
  NOTE_GET: {
    section: 'Home',
    kind: 'read',
    id: 'msttQNbHh0Nh4M6SPlL1E2RRjufluJl7u8nOT5uTFQgtWy0tSVYtWy3yLZRiLpj66qNH/MtAXyvG6/WGYN9/NpyiMKwIvniTyw@@',
    params: '—',
    returns: 'recordset[0].note',
  },
  NOTE_UPDATE: {
    section: 'Home',
    kind: 'write',
    id: '7RRAJLmsoEjqi84dxQbF7Kh1ozVAN6ahXA5OQwcVj+QtWy0tSVYtWy05XrtZ0y+ZrhjMNlwudUA9OK4TsfluJj2y3GWPQbRPCA@@',
    params: "'testo'",
    returns: '—',
  },
  // Ricette
  RICETTE_LIST: {
    section: 'Ricette',
    kind: 'read',
    id: 'uZ+/JDG/PtCiDhrc9YiYjA7p3tmqsWYz8VP7y8teKAUtWy0tSVYtWy3Wbn4vVzxB2eEOOUDqUe1WQxdC6MGkch0xB7XUzRjtKA@@',
    params: 'tipo (1 ricette, 2 schede tecniche)',
    returns: 'recordset: cod_p, nome_ric, composta',
  },
  RICETTE_SEARCH: {
    section: 'Ricette',
    kind: 'read',
    id: '3kLcd3xP1l2BofsQVitE7aFZcbe/Xyf9fQwaS8Gl0DItWy0tSVYtWy0qziERz9x7zeayziwUIMl2Gbjz/C0hTBm6q/nRi8WZGQ@@',
    params: "'testo' (min. 3 caratteri)",
    returns: 'recordset: cod_p, nome_ric',
  },
  SCHEDE_TECNICHE_SEARCH: {
    section: 'Ricette',
    kind: 'read',
    id: 'HxyjRLDEJny8J5KWQJxxH/N2DvGM7E+AAwfZYHDMArgtWy0tSVYtWy00+m4xbqqSUz0i0AekjSqtPiqiWRg1R4smKnwzWs6L9Q@@',
    params: "'testo' (min. 3 caratteri)",
    returns: 'recordset: cod_p, nome_ric',
  },
  RICETTA_GET: {
    section: 'Ricette',
    kind: 'read',
    id: '3K2t3jzxjc+0a0dmj+eRVnotvAfJAoDjYQ/o8SAF2/wtWy0tSVYtWy15LcFBExarLwaeb6649Zrl8Rdbv9FDSmJwaBBc8C3e8g@@',
    params: 'cod_p (anche lista di cod_p per le stampe)',
    returns: 'recordset[0]: testata ricetta',
  },
  RICETTA_SAVE: {
    section: 'Ricette',
    kind: 'write',
    id: 'yQyvP6kwRmZ4Y01UsKulxCxG7MGV0B1QcUxCK6U5SEItWy0tSVYtWy2d8paOBfaJ5qGKfIV63SdsTxDcVhwM2zTsER5z6D9tRA@@',
    params: "cod_p, 'nome_ric', 'procedimento', prezzo_vendita, peso_effettivo, @out_id",
    returns: 'output[0].out_id = cod_p',
  },
  RICETTA_DELETE: {
    section: 'Ricette',
    kind: 'write',
    id: 'bLOf0dGTa+GDJaEG232HA2DR7U2p+79ptLfo/nJDQXktWy0tSVYtWy33s2LNhx4WwU+524qvbddJQUhdRkrjlIEXDYj5rB8vhQ@@',
    params: 'cod_p',
    returns: '—',
  },
  RICETTA_RIGHE: {
    section: 'Ricette',
    kind: 'read',
    id: 'SK1mkQH9EPMbEjkXjVKh208J+h4RyoSZdYvjFW/IwVEtWy0tSVYtWy13aAC10tFq5lY4fyaPFRki0Z709DrH0ocLUEzAss/mUw@@',
    params: 'cod_p',
    returns: 'recordset: id, nome, quantita, perc, ricettaid, escludi_peso',
  },
  RICETTA_RIGA_INSERT: {
    section: 'Ricette',
    kind: 'write',
    id: '3FdtgGhTrxqXmygCCFfZC42j7tE0rFd0h9sihx5l9dAtWy0tSVYtWy3J487uKuF6tzHQ4E0jkvcdftWCBjuP1hUEY2rMzQw5dA@@',
    params: "'nome', quantita, ricettaid, cod_p, ingredienteid",
    returns: '—',
  },
  RICETTA_RIGA_UPDATE: {
    section: 'Ricette',
    kind: 'write',
    id: '6zQerYGHbHjqJ2mcZ0Cq7s6u4WvD9BUcZNrwCU6lIs1nWPVmS5uQHPSLCfdDxsBrKqIfnpEzfVTKbrHits8xAi1bLS1JVi1bLdVYqY1PE/RxFVIKfNtzGacSHOvQPRefO+sHYpJEM1Vb',
    params: "id, 'nome', quantita, ricettaid, cod_p, escludi_peso (1/0)",
    returns: '—',
  },
  RICETTA_RIGA_DELETE: {
    section: 'Ricette',
    kind: 'write',
    id: 'vfJfFKZbzrsaJb7bIJecJqRgXqZvAc6fabCR8kZsd54tWy0tSVYtWy08zCYMCPxN5BXakZn0lgF2O3YSA7SIA4b8KsDaOqkiew@@',
    params: 'id, cod_p',
    returns: '—',
  },
  RICETTA_RIGA_MOVE: {
    section: 'Ricette',
    kind: 'write',
    id: '3mCyL/kBibh2lxoVmwfXrDPeU5rjJJ7fj0BElNWNGMktWy0tSVYtWy2QzxShP4q87m0hlQWrr6NcMc9AyewbbxiMqrPsK6c0Lg@@',
    params: 'id, nuova posizione (da 1), cod_p',
    returns: '—',
  },
  RICETTA_SOTTORICETTE: {
    section: 'Ricette',
    kind: 'read',
    id: 'VwCLXZp2b7f0ntDBmDtjQiMqA71icSP05BfmU0Opi4ydvEX+uB0U2OIODrusGLmNjWldKOX7EhnVg0nsIWMR4S1bLS1JVi1bLQBR2FofNJE57bLSH6oD630781d1Qx+bHhnMTeAjnNz7',
    params: 'cod_p',
    returns: 'recordset: ricettaid',
  },
  RICETTA_FOODCOST_RIGHE: {
    section: 'Ricette',
    kind: 'read',
    id: 'LFC27QWysxqH1e4JTynZrvTHeDkIVVqZltWRciikjx8tWy0tSVYtWy3Km2VOTGisd/Rk3YKgL0fvR/aNOscBfJZfx6MapREbCg@@',
    params: 'cod_p, listinoid',
    returns: 'recordset: descrizione, peso, kcal, foodcost',
  },
  RICETTA_FOODCOST_TOTALI: {
    section: 'Ricette',
    kind: 'read',
    id: 'qowr/0gbIcivI7tzuXF3CcuV980mPwzGQU+See/fYNMtWy0tSVYtWy3CP0PrzJ6X9m1jn4Z+ig0OxeCGFi2Pu2EwfFZDO7S8pw@@',
    params: 'cod_p, listinoid',
    returns:
      'recordset[0]: peso, foodcost, kcal, peso_effettivo, prezzo_lordo_vendita, ratio, prezzo_netto_vendita, margine_netto',
  },
  // Ingredienti
  INGREDIENTI_LIST: {
    section: 'Ingredienti',
    kind: 'read',
    id: '92Z51ruEBMB16QsGuLCg5IRMITJbElTu04zeQyDQ8hwtWy0tSVYtWy3NfTOuxIemB4ik5YY3EihNRNShSM0huP/3RNSMWzBEiw@@',
    params: '—',
    returns: 'recordset: id, descrizione',
  },
  INGREDIENTI_SEARCH: {
    section: 'Ingredienti',
    kind: 'read',
    id: 'dXBEtMkB3PLRn2LH7MgbpuJfe+O2GZXluu2mGitXWOAtWy0tSVYtWy2WminOAV2ecbjmo5i38HGB03aIxjfUYb5d82FkLu4EGg@@',
    params: "'testo' (min. 3 caratteri)",
    returns: 'recordset: id, descrizione',
  },
  CATEGORIE_INGREDIENTI_LIST: {
    section: 'Ingredienti',
    kind: 'read',
    id: 'gKAvUn6c5bcp110Jh/vcbsnEbwctvJY0zl6gC0K3qa4tWy0tSVYtWy1H1JD+sBUdce4kGbfi8PFOJ6glv1neuYU/19MzXKDDSQ@@',
    params: '—',
    returns: 'recordset: id, descrizione',
  },
  // Listini
  LISTINI_LIST: {
    section: 'Listini',
    kind: 'read',
    id: 'BnnFe0vU9aHbFGDCdwhl3h+5nSiRtsLXHgSRgQ803PAtWy0tSVYtWy3oQdVT2zI26QCrxbZr7SBgQ0QqM/cJWYN2qNm3Fq18Lw@@',
    params: '—',
    returns: 'recordset: id, descrizione, aliquota',
  },
  LISTINO_SAVE: {
    section: 'Listini',
    kind: 'write',
    id: '+qE5v3SYnfwew9ERUdNFtDBPcIEX1WHvlPw2rWnt9Z4tWy0tSVYtWy32eWs2dLQzwdu3PT0V1eHN6VOHoiA8WwUBNx9X9PtdvA@@',
    params: "id (0 = nuovo), 'descrizione', aliquota",
    returns: '—',
  },
  LISTINO_DELETE: {
    section: 'Listini',
    kind: 'write',
    id: 'O8ucerAGcmc2Pe61cYP8sNIGcx1t13A4chm0RwJc+eYtWy0tSVYtWy1qBXDOjMpc/IvwECjY/mIGAU97Ykeme0fjs4mW6qbRXQ@@',
    params: 'id',
    returns: '—',
  },
  LISTINO_RIGHE: {
    section: 'Listini',
    kind: 'read',
    id: 'j8nnE18DvMJLJn72/pLhFHuvrOA97O1D70EeY0K28/otWy0tSVYtWy1k5ipImnHJdjEgS2084WWHruF1SwXI5uZouBYSWHPGGQ@@',
    params: 'listinoid, categoria (0 tutte, 999 senza categoria)',
    returns: 'recordset: righe del listino',
  },
  LISTINO_RIGA_UPDATE: {
    section: 'Listini',
    kind: 'write',
    id: '/nGnbEpkUi0vOg4i6e1iuEGuxg69lsTmVCr8YyLq268tWy0tSVYtWy3L2b8m+30DhYzDhrNYxDVYk6RvH3uhYOxox9hDnFFDyQ@@',
    params: "id, scarto, grammatura, prezzo, categoriaid, kcal, 'descrizione', 'provenienza'",
    returns: '—',
  },
  LISTINO_RIGA_DELETE: {
    section: 'Listini',
    kind: 'write',
    id: 'OemnSwfiRPzAVbNM8+3RBZ4O4zVb5T9yN53H7Ax02YwtWy0tSVYtWy0lxrGjs502JyZQihu3oKcFrDNuTa+3V95N9HRsztRp2A@@',
    params: 'id',
    returns: '—',
  },
  LISTINO_ADD_INGREDIENTE: {
    section: 'Listini',
    kind: 'write',
    id: 'E+pKhhlKoT3QoiETImqtg7Tm6Zt2Hw828idhcpov3FeYPL2p7Y+IYRhDaAM1DR/OZYyzo/TQq8WD17k93BrohS1bLS1JVi1bLddOB+8ied/iwzy2sftWM7NH2B+A3DlBQJmKEMJu0DNp',
    params: 'listinoid, ingredienteid',
    returns: '—',
  },
  LISTINO_ADD_SCHEDA_TECNICA: {
    section: 'Listini',
    kind: 'write',
    id: 'M+znAuYqN5Ug1l2iGVkxduf1lbRlT1UuSoxLW1oid8stWy0tSVYtWy34EKDV2l7UJrjG/oWkhSl8rBxmw+GSDbr4MKJeU8pXfA@@',
    params: 'listinoid, cod_p',
    returns: '—',
  },
  LISTINO_ADD_MENU: {
    section: 'Listini',
    kind: 'write',
    id: 'QYJrZrRzOMFO3XpMeU0AeUWJZrkcEqIpC0nohJJeHBotWy0tSVYtWy1dOzu+Lbh7TikceENNj8rI2N6VEbINKQOJyCJc6k2FSg@@',
    params: 'menuid, listinoid (ordine invertito rispetto agli altri)',
    returns: '—',
  },
  // Menù
  MENU_LIST: {
    section: 'Menù',
    kind: 'read',
    id: 'okb5t42MzxMMO10EgkksbFQpXCzgQLrxVnqW8dDhrW0tWy0tSVYtWy2QU3GxVikgfK/sdvifCsRO5yJOE90sdeoUckFl95Ocfg@@',
    params: '—',
    returns: 'recordset: id, descrizione, tipo, pax, perc_ricetta',
  },
  MENU_GET: {
    section: 'Menù',
    kind: 'read',
    id: 'K3JkUG7Hy1/chWxotpmDKn1FOCiRcA9/dx2Fu6QMRL8tWy0tSVYtWy1uvOoRTQ4JicWvhMJMzdxojl+4bSC4yeD1RFwsdpoPJg@@',
    params: 'id',
    returns: 'recordset[0]: menù',
  },
  MENU_INSERT: {
    section: 'Menù',
    kind: 'write',
    id: 'nQ6vGlNTQWOFq9x+Eo5WHKSu26dR8u+cVJ4yRdbgFyEtWy0tSVYtWy17tl03kprmq8PVPclI5j0NKh4awp8QeZinUz6gvwlRSw@@',
    params: "0, 'descrizione', tipo, 0, 0",
    returns: '—',
  },
  MENU_UPDATE: {
    section: 'Menù',
    kind: 'write',
    id: 'WddXaeNoWWXfUYNDtmREohVHFM/7T/G7ffefI3q3RE8tWy0tSVYtWy3QneYethYCTEyg74Y9QyTQBX0Nt0lqHoTn12NCP6P1og@@',
    params: "id, 'descrizione', tipo",
    returns: '—',
  },
  MENU_DELETE: {
    section: 'Menù',
    kind: 'write',
    id: 'b20k0izyEWj8NwW0XI+4P2G7glsRp2Np4K9edlm57/ktWy0tSVYtWy2mhb68JrCq7bjwMdEzlVlt7b8aTBmEnARp939rBwssnQ@@',
    params: 'id',
    returns: '—',
  },
  MENU_CATEGORIE_LIST: {
    section: 'Menù',
    kind: 'read',
    id: 'FNopVUZX6gB8wiOOkcYZoNc/DQsOMebhfWb9Uy5bteItWy0tSVYtWy2RMZrggPg/kUT4un9OQHLCOS1ESKsrvLjZFAvn5tp3VQ@@',
    params: '—',
    returns: 'recordset: id, descrizione',
  },
  MENU_ALLA_CARTA_RIGHE: {
    section: 'Menù',
    kind: 'read',
    id: 'psv6VQSAtEEbFZMQFsqECpPHcS39sQCLkeYlWTsSz+QtWy0tSVYtWy3Yp+JgJC//klU7QOi+O80sdHpj9guvh0v/3I34nk2LMg@@',
    params: 'menuid, listinoid',
    returns: 'recordset: tipo 1 = categoria, tipo 2 = piatto',
  },
  MENU_EVENTO_RIGHE: {
    section: 'Menù',
    kind: 'read',
    id: 'gmWVJZP+UGV9KGcRG53D30i0ozWILb/EMajQiDrIEastWy0tSVYtWy3BMu7OQxzscLI2Tq9rx7i26t6Ra97143uOpKI178zF1w@@',
    params: 'menuid, listinoid',
    returns: 'recordset: tipo 1 = piatto, tipo 2 = separatore',
  },
  MENU_RIGA_INSERT: {
    section: 'Menù',
    kind: 'write',
    id: '4EKFMSLcQErqesydVFFs5MsgUMVAnsk6dEJL6HKiuJ4tWy0tSVYtWy3rWCf0m7d18zKWD0qTdpZ5nrElD4jbP/gbWu8yWlij+A@@',
    params: 'menuid, cod_p, menucategoriaid (0 per gli eventi)',
    returns: '—',
  },
  MENU_RIGA_DELETE: {
    section: 'Menù',
    kind: 'write',
    id: 'ucPKP4vgLwFswQYd3kYSXH49AtOVNz6n57HE4QChZOAtWy0tSVYtWy1cBMOHmEBYZ5ahYrEc8UnPWdkZo4MLYEwx/AiyDiHvsw@@',
    params: 'id',
    returns: '—',
  },
  MENU_RIGA_MOVE: {
    section: 'Menù',
    kind: 'write',
    id: 'wQgcfZjoo4BsKUwn1t0+NbzoCkWck6mkuw/a9KY/nXpVZXHo0QuYVoGlQ7vNS2lxQXzp7HvVq3pM3+2UW0H3Vy1bLS1JVi1bLdUd42OAYsvyHLgHO9HEb2f4tL/vbUcenrRISZDDpJiS',
    params: 'id, nuova posizione (da 1), menuid',
    returns: '—',
  },
  MENU_SEPARATORE_INSERT: {
    section: 'Menù',
    kind: 'write',
    id: 'nvNvQc1GDrC4lRSoWH69eswNyldEoanRYJv4G/68vZMtWy0tSVYtWy0Y/+aKGhSOEdnrEoo8wv9Rl57gUsu4PSBzUN36HmUgBQ@@',
    params: 'id riga sopra il separatore, menuid',
    returns: '—',
  },
  MENU_SEPARATORE_DELETE: {
    section: 'Menù',
    kind: 'write',
    id: 'TSjQ4Ux8su/QtywQgqrzwWVeCYI2bozUYh64WUtMaYQtWy0tSVYtWy1fw6mgUpkDGe+PLDd01VCvb2K7SCePco+lVTA+rbxubg@@',
    params: 'id',
    returns: '—',
  },
  MENU_COPERTI_UPDATE: {
    section: 'Menù',
    kind: 'write',
    id: 'fqSIBghvRnSQ3MgfxEa5hzSJrTnuUrl/KmoPJqpLVuotWy0tSVYtWy0bKOK/0/Gx2zq8WP1fh0DpzYkmaXcymyb9qV+FiPj+HQ@@',
    params: 'menuid, pax, perc_ricetta',
    returns: '—',
  },
  MENU_TOTALI: {
    section: 'Menù',
    kind: 'read',
    id: 'AhzhmjtF+z/CNSybI+oPMsvY8bgo02n2+Kccc5ifI44tWy0tSVYtWy2A3OleBbhIztblymLHcptfGLTotAqZ5MFdbdj4eyjhaA@@',
    params: 'menuid, listinoid',
    returns: 'recordset[0]: totali per coperto e per menù',
  },
  // Dizionario ingredienti
  DIZIONARIO_ALIMENTI: {
    section: 'Dizionario ingredienti',
    kind: 'read',
    id: 'PZ1+HZdXNvLpU0AZIUk3rWpubGUzhymuevOJS2VGErUtWy0tSVYtWy0iUErMQX3OPVw/8cT4xk1K8L8Bc9Hoq4rbP3xl4f+TOg@@',
    params: '—',
    returns:
      'recordset: Ali_desc, Ali_kcal, Ali_edi, Ali_prot, Ali_anim, Ali_veg, Ali_glu, Ali_amid, Ali_lup',
  },
  // Schede di produzione
  SCHEDE_LIST: {
    section: 'Schede di produzione',
    kind: 'read',
    id: 'JF8yXz5TOp18Sotb5VMkfjvUv8HmSOtIm4S02S8XjQ4tWy0tSVYtWy1YFqLxfMIhA3RMGauQYR2m5e5tPNHBFW8t1VyFVpA8lg@@',
    params: '—',
    returns: 'recordset: id, descrizione',
  },
  SCHEDA_SAVE: {
    section: 'Schede di produzione',
    kind: 'write',
    id: 'xHdQPwuFw1H1KO/cRHQlPrTaWgxmNT3nS5b9YaOBlW4tWy0tSVYtWy04WGL10k1ciZBMp7DlMdlugRxaidsNbmKfPeBzmzmpxQ@@',
    params: "id (0 = nuova), 'descrizione'",
    returns: '—',
  },
  SCHEDA_DELETE: {
    section: 'Schede di produzione',
    kind: 'write',
    id: 'b6MZgUoZ3Wk49DsGooqOlsxO+MzfsReH/y0uLX63xF4tWy0tSVYtWy33pNRXlrm4nwQ988rgLtrOLEvfmvS36E+aklKoi80BPA@@',
    params: 'id',
    returns: '—',
  },
  SCHEDA_RIGHE: {
    section: 'Schede di produzione',
    kind: 'read',
    id: 'ZGrBRm2wXfzaxA55wgbIWsB1/YmoPntkZMcM/cQjtLAtWy0tSVYtWy1JhzOXXh74oQxLQr2i2SwqPirx4VWWefINmcScc4m97g@@',
    params: 'id scheda',
    returns: 'recordset: id, ricettaid',
  },
  SCHEDA_RIGA_INSERT: {
    section: 'Schede di produzione',
    kind: 'write',
    id: 'IlbwuISwJ/DBW0uy+ORTu0Ahc/u3Y+nIjqrQ1sd/PLADIHhO//BtdcHkAh+NtCRHVjdQUWhZ9BkJCQHT2xxBSy1bLS1JVi1bLfEH0UNkSMB7zAKeURhyfVO2o9Fth+h9BzgvVLtirIfg',
    params: 'id scheda, cod_p',
    returns: '—',
  },
  SCHEDA_RIGA_DELETE: {
    section: 'Schede di produzione',
    kind: 'write',
    id: 'S+jzb0ADwezeBPQYjHQC4GeltNyU5EsXIlR6m2gN66aa8pPcbUz8wxgmfuhRBA+lcRVOKKJLsoLPnpxoNA4g0C1bLS1JVi1bLaIfIFJTkiW5pAZxdtBC8yhE8eN3wnpirAbLS5tohJ7U',
    params: 'id',
    returns: '—',
  },
  // Archivio documenti
  ARCHIVIO_LIST: {
    section: 'Archivio documenti',
    kind: 'read',
    id: '0i2+RmInGMX0DvOaBMb2+YgiKEYyPyb1UckrhmUoRUotWy0tSVYtWy0xLsiHvQYzJJ7lAyA1aGtvSXKul9MHKkoycGAVlT+pvg@@',
    params: 'folderid, @foldername, @parentid, @parentname',
    returns: 'recordset: file e cartelle; output[0]: foldername, parentid, parentname',
  },
  ARCHIVIO_CARTELLE_TREE: {
    section: 'Archivio documenti',
    kind: 'read',
    id: 'Ayl+LWaNzmB0jK5bAt7dDw2s3Y1r3R3eas1IvS+HvCwtWy0tSVYtWy01yGI+Hwdj8Xd6HsSTttvNfEiaHHnOlhVgEphfAue/5g@@',
    params: '—',
    returns: 'recordset: id, descrizione (percorso)',
  },
  ARCHIVIO_CARTELLA_INSERT: {
    section: 'Archivio documenti',
    kind: 'write',
    id: 'dNJI9LXEVkvhVA0PaJtwD6L1q6tfA1ZXsaZMJyuxlAUtWy0tSVYtWy1nspxg4PgQPJXIYQsxTVgBw9NiqJFN6hL09UIyi0ejrQ@@',
    params: "'descrizione', folderid padre",
    returns: '—',
  },
  ARCHIVIO_CARTELLA_RENAME: {
    section: 'Archivio documenti',
    kind: 'write',
    id: 'EO8JC8YQlb1qMkXVspBpN0TSg51g6MJE8AgoukLdy0stWy0tSVYtWy2+vCVIYV+sszqVEKfxn6c9KFZM1vtSrQBhvXMBKxU5iw@@',
    params: "folderid, 'descrizione'",
    returns: '—',
  },
  ARCHIVIO_CARTELLA_DELETE: {
    section: 'Archivio documenti',
    kind: 'write',
    id: '2ymowsy6h5RjmGLLwyCnmec4Xg5+Q3awNSSt6FXHz0ctWy0tSVYtWy3STQS3Onw2HQ6AGQvD8UN22C/Fwfi5L0YoEcLLJhH7+Q@@',
    params: 'folderid (elimina anche il contenuto)',
    returns: '—',
  },
  ARCHIVIO_FILE_INSERT: {
    section: 'Archivio documenti',
    kind: 'write',
    id: 'aQWu1SmmaITFs0wPPtAi4mvH+ZEphShyYYeUM98pg4ItWy0tSVYtWy1e+2qzPC9u9O9elSJdaZHz9f7O3jqBQcRNBlkfcApwog@@',
    params: "'nome', 'nome', folderid, size, 'type', @out_id",
    returns: 'output[0].out_id = arc_codi',
  },
  ARCHIVIO_FILE_MOVE: {
    section: 'Archivio documenti',
    kind: 'write',
    id: 'wVp8CePj9GWqbn4+9PSPrfcnBgJy5X6770MUTmuu8VEtWy0tSVYtWy2811ekJtlErGybjvOQXCisQNJvW7NZXC65kgNNldAyog@@',
    params: 'arc_codi, folderid destinazione',
    returns: '—',
  },
  ARCHIVIO_FILE_DELETE: {
    section: 'Archivio documenti',
    kind: 'write',
    id: '2H6fgL8RL3pOrFGxXCopTYpWYOhLkBlwYhnnhWceTe4tWy0tSVYtWy1fTzDMAyCc1Um89Bg3UOXRiuG1dWW+NMqxJksng9UkOg@@',
    params: 'arc_codi',
    returns: '—',
  },
} as const satisfies Record<string, ProcessDefinition>;

/** Process usati solo dalle pagine Ingredienti/Ingrediente, eliminate nel porting. */
export const UNUSED_PROCESS_PREFIXES = {
  INGREDIENTI_ANAGRAFICA_LIST: 'bbtabTid',
  INGREDIENTE_GET: 'Xi6OhhAR',
  INGREDIENTE_SAVE: 'ITzKByQO',
  INGREDIENTE_DELETE: 'p2d+TtQ/',
} as const;
